### ISSUE TITLE
Filter items by timestamp

### ISSUE THREAD

**Issue by lissertations** [hughrun/pocket-snack#26]
Add an option in `settings.py` whereby a user can opt to keep everything they've added in the last day/week/month/etc in their list, and stash the rest, or vice versa. Basically an option to filter by timestamp. (Please)

**Comment by hughrun** [comment]
this could also potentially be used with `lucky_dip`

**Comment by hughrun** [comment]
Looking at this now. I think it should be a flag rather than in `options.py`. Could work something like:

`--stash --older_than_days 7` => stash everything added more than a week ago
`--stash --newer_than_days 2` => stash everything added more recently than 2 days ago

`--lucky_dip --newer_than_days 14` => lucky dip but only retrieving items added more recently than 2 weeks (not sure this is actually possible).
